### ISSUE TITLE
make custom social card for embeds

### ISSUE THREAD

**Issue by zweek** [TF2SR/TF2SR-Wiki#11]

**Comment by Nextracer1** [comment]
what is a social card

**Comment by zweek** [comment]
![Screenshot_20230630_123830_Discord.jpg](https://github.com/TF2SR/TF2SR-Wiki/assets/70382336/6a92efbe-811c-4a99-bd94-181f366b3200)
This thingy, it's still using the docusaurus default atm

**Comment by taskinoz** [comment]
I created a basic social card from the logo #54
